(function (global) {
  'use strict';

  const SOURCE_FINGERPRINT = '8f4752c88777adc4386f8703e92b6266416fb78eb74a5f817a306a3dc72a9ede';
  const rung = (id, label, position, recommendedDecision = 'seek-amendment', options = {}) => ({ rung: id, label, position, recommendedDecision, ...options });
  const module = (id, title, clauseTypes, applicability, standardPosition, whyItMatters, checks, fallbackLadder, relatedModules = [], escalationTriggers = []) => ({
    id, revision: '2026-08-22', title, clauseTypes, applicability, standardPosition, whyItMatters, checks, fallbackLadder, relatedModules, escalationTriggers
  });
  const SOURCE_MODULE_REGISTRY = [
    ['A-00','Deal-Level Trade Map'],['A-01','Agreement Structure & Order of Precedence'],['A-04','Change Control'],
    ['B-01','Service Levels & Service Credits'],['B-02','Acceptance & Deemed Acceptance'],
    ['C-03','Personnel & Staffing'],['C-04','Staff Augmentation'],['C-05','Subcontracting'],['C-06','Offshore & Cross-Border Delivery'],['C-07','Non-Solicit / No-Hire'],['C-08','Background Verification'],
    ['D-01','Fees, Invoicing, Payment & Taxes'],['D-02','Price Benchmarking'],['D-03','Most-Favoured Customer'],
    ['E-01','Compliance with Laws'],['E-02','Regulatory Compliance'],['E-03','Data Protection'],['E-04','Information Security'],['E-05','Security Incidents'],['E-06','Audit Rights'],
    ['F-01','IP Ownership'],['F-02','Pre-Existing IP & Tools'],['F-03','Licence Rights'],['F-04','Open-Source Software'],
    ['G-01','AI Components'],
    ['H-01','Warranties'],['H-02','Disclaimers'],['H-03','Indemnities'],['H-04','Limitation of Liability'],['H-05','Exclusions from the Cap'],['H-06','Consequential & Indirect Damages'],['H-07','Insurance'],
    ['I-01','Business Continuity & Disaster Recovery'],['I-02','Termination for Convenience'],['I-03','Termination for Cause'],['I-04','Suspension Rights'],['I-05','Transition & Exit Assistance'],['I-06','Step-in Rights'],['I-07','Force Majeure Suspension'],
    ['J-01','Confidentiality'],['J-02','Dispute Resolution & Governing Law'],['J-03','Assignment & Change of Control'],['J-04','Notices'],['J-05','Entire Agreement & Amendments'],['J-06','Waiver & Severability'],['J-07','Force Majeure'],['J-08','Counterparts & Electronic Execution'],
    ['K-00','Sector Overlay Triage Checklist'],['K-01','BFSI Sector Overlay'],['K-02','Healthcare Sector Overlay'],['K-03','Regulated Outsourcing Overlay'],['K-04','Public Sector Overlay'],
    ['E-03-S1','DPDP Act & Rules 2025 Supplement'],['E-03-S2','GDPR Cross-Border Supplement'],['G-01-S1','AI Regulation Supplement']
  ].map(([id,title])=>{
    const aliases={
      'A-00':['trade map','concession','negotiation sequence'],'A-01':['order of precedence','conflict between documents','agreement structure'],'A-04':['change control','change request','written modification'],
      'C-03':['personnel','key personnel','staffing'],'C-04':['staff augmentation','timesheets','resources'],'C-06':['offshore','cross-border delivery'],'C-07':['non-solicit','no-hire','non solicitation'],'C-08':['background verification','screening'],
      'D-02':['benchmarking','price benchmark'],'D-03':['most favoured customer','most favored customer','mfc'],
      'E-01':['compliance with laws','applicable laws'],'E-02':['regulatory compliance','regulator'],'E-06':['audit','inspect','books and records','access to records'],
      'F-02':['pre-existing ip','background ip','tools'],'F-03':['licence rights','license rights'],'F-04':['open source','oss','copyleft'],
      'H-07':['insurance','insured','policy limits'],'I-01':['business continuity','disaster recovery','bcp','drp'],'I-04':['suspend','suspension'],'I-05':['transition assistance','exit assistance','knowledge transfer'],'I-06':['step-in','step in rights'],'I-07':['force majeure suspension'],
      'J-04':['notice','deemed receipt'],'J-05':['entire agreement','amendments'],'J-06':['waiver','severability'],'J-07':['force majeure','event beyond control'],'J-08':['counterparts','electronic execution','e-signature'],
      'K-01':['bfsi','banking','financial services','insurance sector'],'K-02':['healthcare','patient','clinical','health data'],'K-03':['regulated outsourcing'],'K-04':['public sector','government','public authority','procurement law'],
      'E-03-S1':['dpdp','digital personal data protection'],'E-03-S2':['gdpr','cross-border transfer'],'G-01-S1':['ai act','ai regulation']
    };
    const titleSignals=title.toLowerCase().split(/[^a-z0-9]+/).filter(word=>word.length>4&&!['agreement','services','information','change','control','rights','terms','with','from','overlay','supplement','sector'].includes(word));
    return{id,title,sourceStatus:'indexed',operationalStatus:'not-loaded',topicSignals:[...new Set([...(aliases[id]||[]),...titleSignals])],sourceOnly:true};
  });

  const SUPPLIER_SERVICES_CORE = {
    schemaVersion: 'contract-cockpit-playbook/3', packageId: 'supplier-services-core', name: 'Supplier-side Services Core — contextual playbook', version: '3.2.0', role: 'Supplier',
    jurisdictionAnchor: 'India — verify governing law and matter-specific advice', sourceTitle: 'Supplier Side Contracts Negotiation Playbook 2', sourceFingerprint: SOURCE_FINGERPRINT,
    sourceModuleRegistry: SOURCE_MODULE_REGISTRY,
    contentHash: '87754182e8e13a65af61019e27a5d26f807c446d97dad78c7c43bf6aa7ac8b97', status: 'Contextual operational layer — 20 operational modules with ambient routing across all 55 source modules and supplements. Indexed-only routes are labelled and never fabricate detailed guidance. Verify against the governing source, matter facts and current law',
    modules: [
      module('H-04','Limitation of Liability',['Liability'],{requiredAny:['aggregate liability','liability cap','limitation of liability','maximum liability','uncapped liability','unlimited liability','cap to the liability'],issueRules:[{id:'conditional-cap',label:'Supplier cap appears conditional',any:['cap to the liability','may apply only if','only if expressly agreed']},{id:'asymmetric-cap',label:'Cap may be asymmetric',any:['one party shall have no liability','supplier cap','customer cap','innostars cap']},{id:'no-cap',label:'No effective aggregate cap detected',any:['uncapped liability','unlimited liability','no aggregate cap']}],minEvidence:1},'Use a mutual, aggregate cap tied to a defined fee base and period; preserve only deliberate, narrow carve-outs.','Cap wording, measurement period and carve-outs determine whether the negotiated limit is real or illusory.',['Identify each party’s cap, fee base and measurement period.','Check whether exclusions or indemnities sit outside the cap.','Confirm whether the cap is mutual and aggregate.'],[rung('standard','Standard','Mutual aggregate cap linked to fees paid or payable in the relevant 12-month period.'),rung('fallback-1','Fallback 1','A higher negotiated super-cap only for specified claims, with all other liability inside the general cap.'),rung('walk-away','Escalate','Uncapped or effectively uncapped supplier liability requires leadership approval.','escalate')],['H-03','H-05','H-06'],['No aggregate supplier cap','Customer liability excluded while supplier liability remains broad','Broad indemnity or data claims outside every cap']),
      module('H-03','Indemnities',['Indemnity'],{requiredAny:['indemnify','indemnification','hold harmless','defend'],issueRules:[{id:'first-party',label:'First-party or general loss wording detected',any:['all losses','any losses','suits proceedings claims damages','breach negligence']},{id:'broad-heads',label:'Broad loss heads detected',any:['indirect incidental special consequential','loss of profit','all costs and expenses']}],minEvidence:1},'Limit supplier indemnities to clearly defined third-party claims, with control of defence, cooperation and settlement protections.','A broad first-party or uncapped indemnity can bypass the negotiated liability framework.',['Separate third-party claims from direct losses.','Check defence control and settlement consent.','Check interaction with the liability cap and exclusions.'],[rung('standard','Standard','Specified third-party claims only, subject to defence-control mechanics and the agreed liability framework.'),rung('fallback-1','Fallback 1','Narrow direct-loss recovery only for a defined breach and subject to an express cap.'),rung('walk-away','Escalate','Open-ended, first-party or uncapped indemnity requires approval.','escalate')],['H-04','H-05','F-01','E-03'],['First-party indemnity','Uncontrolled settlement rights','Indemnity excluded from all caps']),
      module('H-05','Exclusions and Carve-outs',['Liability','Indemnity'],{requiredAny:['excluded from the cap','not subject to the cap','carve-out','unlimited liability','shall not apply to'],minEvidence:1},'Keep carve-outs objectively defined, reciprocal where appropriate and limited to risks that cannot reasonably sit within the general cap.','A long carve-out list can remove the economic value of the general liability cap.',['List every cap exclusion.','Test whether each exclusion is mutual.','Check overlap with indemnities, confidentiality, IP and data claims.'],[rung('standard','Standard','Narrow mandatory-law and deliberate-misconduct exclusions only.'),rung('fallback-1','Fallback 1','Use a defined super-cap for selected confidentiality, data or IP exposures.'),rung('walk-away','Escalate','Undefined or cascading exclusions require approval.','escalate')],['H-03','H-04','H-06']),
      module('H-06','Indirect and Consequential Loss',['Liability'],{requiredAny:['consequential damages','consequential loss','indirect damages','indirect loss','loss of profit','special damages','punitive damages'],issueRules:[{id:'one-way-loss',label:'One-way or indemnity-linked loss heads require verification',any:['supplier shall indemnify','customer shall have no liability','lost profits']}],minEvidence:1},'Use a mutual exclusion for indirect and consequential loss, with any negotiated recoverable heads stated precisely.','Drafting labels are interpreted differently across jurisdictions; enumerated loss heads may override the general exclusion.',['Check whether the exclusion is mutual.','Identify enumerated loss heads.','Check governing-law and cap interaction.'],[rung('standard','Standard','Mutual exclusion of indirect and consequential losses.'),rung('fallback-1','Fallback 1','Permit only specifically negotiated direct-loss heads within the aggregate cap.')],['H-03','H-04','H-05']),
      module('E-03','Data Protection',['Data Protection'],{requiredAny:['personal data','data processor','data controller','data fiduciary','data breach','data protection'],minEvidence:1},'Align obligations to actual processing roles, applicable law and documented services; avoid absolute security commitments.','Incorrect role assumptions or unlimited security commitments can create duties disconnected from the service model.',['Confirm roles, jurisdictions and data scope.','Check incident timing and cooperation duties.','Check sub-processing, transfer and audit mechanics.'],[rung('standard','Standard','Role-accurate DPA with reasonable security, incident and assistance obligations.'),rung('fallback-1','Fallback 1','Enhanced commitments only for documented scope, reasonable cost allocation and agreed liability treatment.'),rung('walk-away','Escalate','Unbounded regulatory assistance, absolute security or unlimited data exposure requires privacy and leadership approval.','escalate')],['E-06','H-03','H-04']),
      Object.assign(module('E-04','Information Security',['Data Protection','Services'],{requiredAny:['information security','security controls','iso 27001','security policy','technical and organisational measures','security requirements'],minEvidence:1},'Commit to appropriate, risk-based security controls aligned to the documented services and agreed assurance evidence—not absolute security or unbounded customer policies.','Absolute or continuously changing security obligations can create uninsurable exposure disconnected from the service scope.',['Map security duties to the actual service and data.','Identify incorporated policies, standards and change rights.','Test audit, remediation, incident and liability interactions.'],[
        rung('rung-1','Rung 1 · House position','Risk-based controls appropriate to the services and data, supported by agreed certifications or evidence.','seek-amendment',{knowledgeStatus:'source-structured'}),
        rung('rung-2','Rung 2 · Preferred fallback','Agree named baseline standards and a reasonable remediation process, with material changes handled through change control.','seek-amendment',{knowledgeStatus:'source-structured'}),
        rung('rung-3','Rung 3 · Structured compromise','Accept additional customer controls only where relevant, technically feasible and costed, with equivalent-control flexibility.','seek-amendment',{knowledgeStatus:'source-structured'}),
        rung('rung-4','Rung 4 · Named-approval last resort','Accept a defined elevated control set for this deal only, with Security, Legal and commercial approval and an agreed liability treatment.','escalate',{approvalRequired:true,approver:'Security + Legal + authorised commercial approver',knowledgeStatus:'source-structured'}),
        rung('rung-5','Rung 5 · Walk-away / escalation','Escalate absolute security warranties, unilateral policy change, impossible controls or exposure outside the approved liability architecture.','escalate',{approvalRequired:true,approver:'Leadership / authorised risk owner',escalationOnly:true,knowledgeStatus:'source-structured'})
      ],['E-03','E-05','E-06','H-04'],['Absolute or breach-free security warranty','Unilateral policy changes without feasibility or cost control','Security exposure outside approved caps']),{orientation:{tier:'Tier 1',negotiationHeat:'High',capitalToSpend:'High',typicalLandingZone:'Risk-based controls, objective evidence and controlled change',corePrinciple:'Security commitments must be relevant, feasible, measurable and aligned to liability.'},decisionTable:[{id:'E-04-primary',detectedPattern:'Absolute, dynamic or unscoped security requirements',recommendedAction:'Seek amendment',reason:'The duty may exceed the service design and approved exposure.',targetRung:'rung-2'}],sampleLanguage:'Supplier will maintain appropriate technical and organisational measures proportionate to the Services and risks, evidenced by the agreed assurance materials.',redlineMoves:['Replace absolute outcomes with risk-based controls.','Freeze or control incorporated security policies.','Use equivalent controls and a reasonable remediation plan.'],interactionPoints:[{moduleId:'E-03',reason:'Data roles and scope define relevant controls.'},{moduleId:'E-05',reason:'Incident duties depend on the security boundary.'},{moduleId:'H-04',reason:'Security exposure must sit within the liability architecture.'}],sourceAnchors:['E-04 — Information Security']}),
      Object.assign(module('E-05','Security Incidents',['Data Protection','Services'],{requiredAny:['security incident','data breach','personal data breach','cyber incident','notify within','incident response'],minEvidence:1},'Use a precise incident definition, notification triggered by confirmed material impact, workable timing, controlled communications and proportionate cooperation.','Overbroad triggers and clock-starts can force premature or inaccurate reporting and unlimited response cost.',['Define the incident and affected service boundary.','Check trigger, knowledge standard and notification clock.','Control regulator/customer communications, remediation and costs.'],[
        rung('rung-1','Rung 1 · House position','Notify without undue delay after confirming a material incident affecting Customer data or Services; provide verified updates as the investigation develops.','seek-amendment',{knowledgeStatus:'source-structured'}),
        rung('rung-2','Rung 2 · Preferred fallback','Use a defined hour-based initial notice after confirmation, limited to information reasonably available at that time.','seek-amendment',{knowledgeStatus:'source-structured'}),
        rung('rung-3','Rung 3 · Structured compromise','Accept accelerated notice for critical incidents, with phased reporting and no admission or unverified root-cause obligation.','seek-amendment',{knowledgeStatus:'source-structured'}),
        rung('rung-4','Rung 4 · Named-approval last resort','Accept a shorter trigger only with Security and Privacy approval, a tightly scoped incident definition and controlled external communications.','escalate',{approvalRequired:true,approver:'Security + Privacy + Legal',knowledgeStatus:'source-structured'}),
        rung('rung-5','Rung 5 · Walk-away / escalation','Escalate immediate notice of any suspected event, customer-controlled public statements or unlimited incident costs/liability.','escalate',{approvalRequired:true,approver:'Leadership / authorised risk owner',escalationOnly:true,knowledgeStatus:'source-structured'})
      ],['E-03','E-04','H-04'],['Notice before a material incident is confirmed','Customer-controlled public or regulator statements','Unlimited incident response cost']),{orientation:{tier:'Tier 1',negotiationHeat:'High',capitalToSpend:'High',typicalLandingZone:'Confirmed material incident, phased notice and controlled cooperation',corePrinciple:'Incident duties should support response quality, not punish investigation uncertainty.'},decisionTable:[{id:'E-05-primary',detectedPattern:'Any suspected event or immediate notice with unlimited cooperation',recommendedAction:'Seek amendment',reason:'The trigger and obligations may be operationally impossible.',targetRung:'rung-2'}],sampleLanguage:'Supplier will notify Customer without undue delay after confirming a material Security Incident affecting the Services or Customer Data and will provide updates as verified information becomes available.',redlineMoves:['Define materiality and confirmation.','Use phased reporting.','Control communications, admissions and cost allocation.'],interactionPoints:[{moduleId:'E-04',reason:'Security controls establish the incident boundary.'},{moduleId:'E-03',reason:'Personal-data incidents may trigger separate legal clocks.'},{moduleId:'H-04',reason:'Response cost and claims require cap alignment.'}],sourceAnchors:['E-05 — Security Incidents']}),
      Object.assign(module('G-01','AI Components',['Services','Intellectual Property','Data Protection'],{requiredAny:['ai system','ai tool','ai output','artificial intelligence','machine learning','generative ai','ai model','model output','training data','automated decision'],minEvidence:1},'Identify each AI component and allocate data, output, IP, accuracy, transparency and regulatory duties according to the actual supplier role and use case.','Generic AI clauses can impose provider-level duties on a deployer or integrator and create absolute output or regulatory warranties.',['Inventory models, providers, inputs, outputs and intended uses.','Map training, prompt and output rights.','Check human oversight, prohibited uses, transparency, security and liability.'],[
        rung('rung-1','Rung 1 · House position','Role-accurate AI terms tied to identified components, permitted data, documented use and reasonable safeguards; no absolute output warranty.','seek-amendment',{knowledgeStatus:'source-structured'}),
        rung('rung-2','Rung 2 · Preferred fallback','Accept defined transparency, testing and human-oversight commitments within Supplier control and the agreed service scope.','seek-amendment',{knowledgeStatus:'source-structured'}),
        rung('rung-3','Rung 3 · Structured compromise','Add use-case-specific restrictions, provider flow-downs and limited output assurances with customer responsibilities recorded.','seek-amendment',{knowledgeStatus:'source-structured'}),
        rung('rung-4','Rung 4 · Named-approval last resort','Accept elevated regulated-use obligations only after AI, Privacy, Security and Legal approval, with validated feasibility and liability treatment.','escalate',{approvalRequired:true,approver:'AI governance + Privacy + Security + Legal',knowledgeStatus:'source-structured'}),
        rung('rung-5','Rung 5 · Walk-away / escalation','Escalate prohibited or high-risk use without controls, unrestricted training rights, absolute non-infringement/accuracy warranties or provider duties outside Supplier control.','escalate',{approvalRequired:true,approver:'Leadership / authorised risk owner',escalationOnly:true,knowledgeStatus:'source-structured'})
      ],['E-03','E-04','F-01','H-03','H-04'],['Unrestricted use of customer data for model training','Absolute accuracy or regulatory compliance warranty','High-risk deployment without agreed human oversight']),{orientation:{tier:'Tier 1',negotiationHeat:'High',capitalToSpend:'High',typicalLandingZone:'Component- and use-case-specific duties with shared responsibilities',corePrinciple:'AI risk follows the actual role, component and intended use—not the word “AI”.'},decisionTable:[{id:'G-01-primary',detectedPattern:'Generic AI warranty, unrestricted training or high-risk use',recommendedAction:'Escalate',reason:'The obligation may exceed Supplier control or create regulated-use exposure.',targetRung:'rung-4'}],sampleLanguage:'The parties will identify approved AI Components and intended uses. Supplier will apply the agreed safeguards within its control; Customer remains responsible for its instructions, inputs, human review and deployment decisions.',redlineMoves:['Create an AI component schedule.','Separate provider, deployer and customer responsibilities.','Prohibit unapproved training and absolute output warranties.'],dealOverlays:['AI-enabled services','SaaS','Regulated outsourcing'],supplements:['G-01-S1 AI regulation'],interactionPoints:[{moduleId:'E-03',reason:'Inputs and prompts may contain personal data.'},{moduleId:'F-01',reason:'Training, model and output rights require separate treatment.'},{moduleId:'H-04',reason:'AI claims need an explicit liability position.'}],sourceAnchors:['G-01 — AI Components','G-01-S1 — AI Regulation Supplement']}),
      module('F-01','Intellectual Property Ownership',['Intellectual Property'],{requiredAny:['intellectual property','background ip','background intellectual property','work product','deliverable','ownership'],issueRules:[{id:'background-transfer',label:'Background IP transfer or unusually broad licence requires verification',any:['background ip shall vest','irrevocable perpetual','assigns all intellectual property']}],minEvidence:1},'Supplier retains background tools, know-how and reusable materials; the customer receives the ownership or licence needed for paid deliverables.','Overbroad assignment language can transfer reusable supplier assets and improvements unrelated to the customer-specific deliverable.',['Separate background IP from project deliverables.','Check licence scope for embedded supplier materials.','Address improvements, feedback and third-party materials.'],[rung('standard','Standard','Customer-specific deliverables transfer on payment; supplier background IP remains supplier-owned with a necessary-use licence.'),rung('fallback-1','Fallback 1','Broader deliverable ownership with explicit reusable-material and know-how reservations.'),rung('walk-away','Escalate','Assignment of background IP, generic tools or unrelated improvements requires approval.','escalate')],['H-03','H-04']),
      module('D-01','Fees and Payment',['Fees'],{requiredAny:['fees','invoice','payment terms','payable','set-off','withholding'],issueRules:[{id:'setoff',label:'Broad set-off or withholding right detected',any:['set-off','set off','withhold any amount']}],minEvidence:1},'Use clear invoicing triggers, a defined payment period, tax treatment and a controlled dispute process for genuinely disputed amounts.','Ambiguous acceptance or set-off mechanics can delay payment while service obligations continue.',['Confirm payment period and invoice trigger.','Check set-off, withholding and disputed-invoice mechanics.','Check taxes, expenses and suspension rights.'],[rung('standard','Standard','Undisputed invoices payable within 30 days, with prompt notice of specific disputes.'),rung('fallback-1','Fallback 1','Longer period only with no broad set-off and a clear dispute-resolution timetable.')],['A-04','B-02','H-04','I-02']),
      module('B-01','Service Levels and Credits',['Service Levels'],{requiredAny:['service level','service credit','uptime','availability percentage','response time','resolution time','chronic failure'],requiredCount:1,minEvidence:1},'Use measurable service levels with agreed exclusions, fair reporting and credits as the primary remedy for measured failure.','Unqualified metrics and cumulative remedies can turn operational credits into uncapped damages.',['Confirm metric, measurement window and exclusions.','Check credit calculation and claim process.','Check whether credits are sole remedy and how chronic failure is treated.'],[rung('standard','Standard','Objective metrics, reasonable exclusions and service credits as the primary remedy.'),rung('fallback-1','Fallback 1','Chronic-failure termination after defined repeated misses, without duplicative recovery.')],['I-03']),
      module('A-04','Change Control',['Change Control','Services'],{requiredAny:['change control','change request','variation','change order','scope change'],minEvidence:1},'Require documented scope, schedule and fee impact before a change becomes binding.','Uncontrolled change language can expand delivery obligations without corresponding time or fees.',['Identify who may request a change.','Require impact assessment and signed approval.','Preserve performance of undisputed existing scope.'],[rung('standard','Standard','No scope change is binding until both parties approve its price, timing and responsibility impact.'),rung('fallback-1','Fallback 1','Emergency changes may proceed only under a capped interim authorisation and prompt written confirmation.')],['D-01','B-02']),
      module('B-02','Acceptance',['Services'],{requiredAny:['acceptance criteria','deemed acceptance','acceptance test','reject the deliverable','accept the deliverable'],minEvidence:1},'Use objective acceptance criteria, a short review period and deemed acceptance where no specific rejection is issued.','Open-ended or subjective acceptance can delay payment and extend delivery risk indefinitely.',['Confirm objective criteria.','Check review and cure periods.','Link acceptance to invoicing and change control.'],[rung('standard','Standard','Objective criteria, prompt specific rejection and deemed acceptance after the review period.'),rung('fallback-1','Fallback 1','One defined cure cycle before escalation or termination.')],['A-04','D-01']),
      module('C-05','Subcontracting',['Services','Assignment'],{requiredAny:['subcontract','sub-contractor','subprocessor','sub-processor'],minEvidence:1},'Permit ordinary subcontracting with supplier responsibility and proportionate notice for material delivery subcontractors.','Blanket consent rights can obstruct delivery; unbounded subcontracting can create governance and data risk.',['Check consent versus notice.','Preserve supplier responsibility.','Align subprocessors with data terms.'],[rung('standard','Standard','Supplier may subcontract while remaining responsible; notice for material delivery subcontractors.'),rung('fallback-1','Fallback 1','Consent not to be unreasonably withheld or delayed for named categories.')],['E-03','J-03']),
      module('H-01','Warranties',['Warranties'],{requiredAny:['warrant','warranty','represents and warrants','fit for purpose','error-free'],issueRules:[{id:'absolute-warranty',label:'Absolute or outcome-based warranty detected',any:['error-free','uninterrupted','fit for purpose','all requirements']}],minEvidence:1},'Keep warranties specific, time-bound and tied to professional performance rather than absolute outcomes.','Absolute warranties can become uncapped performance guarantees and duplicate remedies.',['Separate service standard from guaranteed outcome.','Check cure and exclusive remedy.','Align survival and liability.'],[rung('standard','Standard','Services performed with reasonable skill and care; time-limited conformity warranty with cure.'),rung('walk-away','Escalate','Absolute, perpetual or outcome-guaranteed warranty requires approval.','escalate')],['H-04','I-02']),
      module('I-03','Termination for Cause',['Termination'],{requiredAny:['terminate for breach','material breach','insolvency','remedy the breach','termination for cause'],minEvidence:1},'Use reciprocal, defined cause events and a reasonable cure process.','One-way or vague cause rights can create immediate discontinuity and stranded cost.',['Check reciprocity.','Confirm cure periods and insolvency triggers.','Address accrued fees and transition.'],[rung('standard','Standard','Reciprocal material-breach termination after notice and reasonable cure.'),rung('fallback-1','Fallback 1','Immediate termination only for non-curable material breach or insolvency.')],['I-02','D-01']),
      module('I-02','Termination for Convenience',['Termination'],{requiredAny:['termination for convenience','terminate without cause','terminate at any time','without assigning any reason'],issueRules:[{id:'one-way-convenience',label:'One-way convenience right requires verification',any:['customer may terminate','client may terminate','innostars may terminate']}],minEvidence:1},'Avoid one-way convenience termination or protect committed cost, work performed and an orderly wind-down.','Uncompensated convenience termination transfers investment and capacity risk to the supplier.',['Check reciprocity and notice.','Recover committed costs and work performed.','Address transition assistance.'],[rung('standard','Standard','Mutual convenience termination on adequate notice with payment of accrued and committed costs.'),rung('fallback-1','Fallback 1','Customer-only convenience right with a termination charge and minimum notice.'),rung('walk-away','Escalate','Immediate, uncompensated customer convenience termination requires approval.','escalate')],['I-03','D-01','B-01']),
      module('J-01','Confidentiality',['Confidentiality'],{requiredAny:['confidential information','confidentiality','non-disclosure'],minEvidence:1},'Use reciprocal confidentiality obligations, standard exclusions and a practical survival period.','One-way, perpetual or operationally impossible confidentiality duties can obstruct ordinary delivery.',['Check reciprocity and permitted recipients.','Confirm exclusions and compelled disclosure.','Check survival and return/destruction.'],[rung('standard','Standard','Reciprocal confidentiality with standard exclusions and need-to-know disclosure.'),rung('fallback-1','Fallback 1','Longer survival only for genuine trade secrets and protected personal data.')],['H-04']),
      module('J-02','Dispute Resolution',['Governing Law'],{requiredAny:['governing law','exclusive jurisdiction','courts of','arbitration','icc','siac','lcia'],issueRules:[{id:'forum-option',label:'Counterparty forum optionality detected',any:['at its option','may choose','courts or arbitration','option to refer']}],minEvidence:1},'Use a single, predictable governing law and forum appropriate to the deal and enforcement profile.','Unilateral forum optionality increases cost and procedural uncertainty.',['Identify law, court/seat and rules.','Check whether forum choice is unilateral.','Confirm interim-relief and service mechanics.'],[rung('standard','Standard','One agreed governing law and exclusive forum or arbitral seat.'),rung('fallback-1','Fallback 1','Neutral arbitration with defined seat, language and institution.'),rung('walk-away','Escalate','Unilateral multi-forum optionality requires approval.','escalate')],['J-03']),
      module('J-03','Assignment and Change of Control',['Assignment'],{requiredAny:['assign','assignment','transfer','change of control','pledge'],issueRules:[{id:'one-way-assignment',label:'One-way assignment restriction detected',any:['supplier shall not assign','service provider shall not assign']}],minEvidence:1},'Use reciprocal assignment controls with sensible affiliate and transaction exceptions.','One-way restrictions can inhibit restructuring while allowing the customer to transfer freely.',['Check reciprocity.','Include affiliate/reorganisation exceptions.','Distinguish assignment from subcontracting.'],[rung('standard','Standard','Reciprocal consent with affiliate and business-transfer exceptions.'),rung('fallback-1','Fallback 1','Consent not unreasonably withheld, conditioned or delayed.')],['C-05','J-02'])
    ]
  };

  const PLAYBOOK_V3_DETAILS = {
    'H-03': {
      orientation:{tier:'Tier 1',negotiationHeat:'High',capitalToSpend:'High',typicalLandingZone:'Named third-party claims within the agreed liability architecture',corePrinciple:'An indemnity is a targeted claim-allocation tool, not a general warranty or uncapped damages route.'},
      decisionTable:[
        {detectedPattern:'Broad first-party or general-loss indemnity',recommendedAction:'Seek amendment',reason:'Direct-loss recovery should remain within the ordinary breach and liability regime.',targetRung:'rung-1'},
        {detectedPattern:'Third-party claim with defence, notice and settlement controls',recommendedAction:'Accept with changes',reason:'Retain only the defined third-party exposure and procedural protections.',targetRung:'rung-2'},
        {detectedPattern:'Indemnity outside every cap or covering consequential losses',recommendedAction:'Escalate',reason:'The clause may bypass the negotiated economic allocation.',targetRung:'rung-5'}
      ],
      sampleLanguage:'Supplier will indemnify Customer against finally awarded third-party claims to the extent arising from the specifically identified indemnified event, subject to prompt notice, Supplier control of the defence and no settlement imposing non-monetary obligations without consent.',
      redlineMoves:['Replace “all losses arising from breach” with named third-party claims.','Add notice, defence-control, cooperation and settlement-consent mechanics.','Expressly align indemnity exposure with H-04/H-05 and prevent double recovery.'],
      pushback:{soft:'We can stand behind defined third-party risks, but ordinary breach losses should follow the agreed remedies and cap.',strong:'We cannot accept a general first-party or uncapped indemnity that bypasses the liability bargain.'},
      dealOverlays:['Managed services','Technology implementation','SaaS','AI-enabled services'],supplements:['E-03-S1 DPDP','E-03-S2 GDPR cross-border'],sourceAnchors:['H-03 — Indemnities','H-03 junior-lawyer checklist']
    },
    'H-04': {
      orientation:{tier:'Tier 1',negotiationHeat:'High',capitalToSpend:'High',typicalLandingZone:'Mutual aggregate fee-linked cap with deliberate sub-caps',corePrinciple:'The cap must be mutual, aggregate, measurable and preserved from carve-out erosion.'},
      decisionTable:[
        {detectedPattern:'No confirmed aggregate Supplier cap or cap conditional on an annex',recommendedAction:'Escalate',reason:'The Supplier may be effectively uncapped.',targetRung:'rung-5'},
        {detectedPattern:'Mutual general cap with narrow, defined sub-caps',recommendedAction:'Accept with changes',reason:'Confirm fee base, period, aggregation and carve-outs.',targetRung:'rung-2'},
        {detectedPattern:'Customer capped while Supplier exposure remains broad',recommendedAction:'Seek amendment',reason:'The allocation is structurally asymmetric.',targetRung:'rung-1'}
      ],
      sampleLanguage:'Each party’s aggregate liability arising out of or in connection with the Agreement will not exceed the fees paid or payable under the affected Services during the twelve months preceding the event giving rise to liability.',
      redlineMoves:['Create an express aggregate Supplier cap.','Define the fee base and measurement period.','Move selected IP/data risks into negotiated sub-caps rather than uncapped carve-outs.'],
      pushback:{soft:'A clear aggregate cap lets both sides price and insure the engagement rationally.',strong:'An absent, conditional or illusory Supplier cap requires leadership approval.'},
      dealOverlays:['Managed services','Fixed-fee project','Staff augmentation','SaaS','Regulated outsourcing'],sourceAnchors:['H-04 — Limitation of Liability','H-04 five-rung ladder']
    },
    'B-02': {
      orientation:{tier:'Tier 1',negotiationHeat:'Medium',capitalToSpend:'High',typicalLandingZone:'Objective criteria, a short rejection window and acceptance by silence',corePrinciple:'Acceptance must be objectively testable and cannot remain open indefinitely.'},
      decisionTable:[
        {detectedPattern:'No objective criteria or no review deadline',recommendedAction:'Seek amendment',reason:'Payment and warranty commencement may remain uncertain.',targetRung:'rung-1'},
        {detectedPattern:'Specific rejection window and acceptance by silence',recommendedAction:'Accept with changes',reason:'Verify criteria, rejection reasons and cure cycles.',targetRung:'rung-2'}
      ],
      sampleLanguage:'Customer will accept or reject a Deliverable against the agreed Acceptance Criteria within ten Business Days, stating specific material non-conformities; otherwise the Deliverable is deemed accepted.',
      redlineMoves:['Add objective Acceptance Criteria.','Require specific rejection reasons within a fixed window.','Limit cure cycles and align acceptance with invoicing and warranty start.'],
      pushback:{soft:'A defined review window protects the project plan while preserving a genuine rejection right.',strong:'Open-ended subjective acceptance cannot control payment or warranty commencement.'},
      sourceAnchors:['B-02 — Acceptance & Deemed Acceptance']
    },
    'A-04': {
      orientation:{tier:'Tier 1',negotiationHeat:'Medium',capitalToSpend:'High',typicalLandingZone:'No binding change without written scope, fee and schedule agreement',corePrinciple:'Changed scope must carry corresponding commercial and delivery consequences.'},
      decisionTable:[{detectedPattern:'Change can be directed without agreed impact',recommendedAction:'Seek amendment',reason:'The Supplier may absorb unpriced scope and schedule risk.',targetRung:'rung-1'}],
      sampleLanguage:'No change to the Services is binding until the parties sign a Change Order recording the scope, assumptions, fees, schedule and responsibility impact.',
      redlineMoves:['Require an impact assessment.','Require authorised written approval.','Permit suspension of disputed changed scope while existing scope continues.'],
      pushback:{soft:'We can respond quickly to change once its impact is recorded.',strong:'We cannot perform changed scope without agreed time and fee consequences.'},sourceAnchors:['A-04 — Change Control']
    },
    'D-01': {
      orientation:{tier:'Tier 1',negotiationHeat:'High',capitalToSpend:'High',typicalLandingZone:'Clear invoice trigger, 30-day payment and narrow disputed-amount withholding',corePrinciple:'Payment mechanics must protect cash flow and remain aligned with acceptance, change and termination.'},
      decisionTable:[{detectedPattern:'Broad or cross-agreement set-off',recommendedAction:'Seek amendment',reason:'Unrelated claims can disrupt cash flow on performed Services.',targetRung:'rung-1'}],
      sampleLanguage:'Customer will pay undisputed invoices within thirty days. Any dispute must identify the specific amount and basis promptly; all undisputed amounts remain payable without set-off.',
      redlineMoves:['Limit withholding to the genuinely disputed invoice amount.','Remove affiliate or cross-agreement set-off.','Add notice, escalation, interest and suspension mechanics.'],
      pushback:{soft:'Invoice disputes can be addressed without withholding unrelated or undisputed amounts.',strong:'Cross-agreement set-off is not an acceptable substitute for the dispute process.'},sourceAnchors:['D-01 — Fees, Invoicing, Payment & Taxes']
    },
    'I-03': {
      orientation:{tier:'Tier 1',negotiationHeat:'High',capitalToSpend:'High',typicalLandingZone:'Material breach, valid notice and a workable cure path',corePrinciple:'Cause termination should respond to material, identified and uncured failure.'},
      decisionTable:[{detectedPattern:'Immediate or any-breach termination without cure',recommendedAction:'Seek amendment',reason:'Minor or remediable failures should not trigger immediate exit.',targetRung:'rung-1'}],
      sampleLanguage:'Either party may terminate for a material breach that remains uncured thirty days after a notice describing the breach and required remedy.',
      redlineMoves:['Limit trigger to material breach.','Add a valid notice and cure period.','Treat invalid cause termination as convenience termination.'],
      pushback:{soft:'A materiality and cure process reduces avoidable service disruption.',strong:'Immediate termination for any breach is disproportionate and requires escalation.'},sourceAnchors:['I-03 — Termination for Cause']
    },
    'I-02': {
      orientation:{tier:'Tier 1',negotiationHeat:'High',capitalToSpend:'High',typicalLandingZone:'Adequate notice plus accrued fees, committed costs and orderly wind-down',corePrinciple:'A discretionary exit should not transfer stranded investment to the Supplier.'},
      decisionTable:[{detectedPattern:'Customer-only convenience termination without cost recovery',recommendedAction:'Escalate',reason:'The Supplier bears committed capacity and demobilisation risk.',targetRung:'rung-5'}],
      sampleLanguage:'Customer may terminate for convenience on ninety days’ notice and will pay accrued fees, unavoidable committed costs and the agreed termination charge.',
      redlineMoves:['Increase notice.','Recover work performed and committed costs.','Protect minimum commitments and make transition separately chargeable.'],
      pushback:{soft:'Discretionary exit is workable if the economic wind-down is covered.',strong:'Immediate uncompensated convenience termination requires leadership approval.'},sourceAnchors:['I-02 — Termination for Convenience']
    },
    'J-02': {
      orientation:{tier:'Tier 2',negotiationHeat:'Medium',capitalToSpend:'Medium',typicalLandingZone:'One predictable law and forum or a defined neutral arbitration',corePrinciple:'Forum optionality should not belong to one party.'},
      decisionTable:[{detectedPattern:'Counterparty may choose among multiple courts and arbitration',recommendedAction:'Seek amendment',reason:'Unilateral optionality increases cost and procedural uncertainty.',targetRung:'rung-1'}],
      sampleLanguage:'The Agreement is governed by the agreed law and disputes are finally resolved by arbitration under the stated rules, seat and language.',
      redlineMoves:['Select one governing law and forum.','Define seat, institution, language and number of arbitrators.','Make interim-relief mechanics reciprocal.'],
      pushback:{soft:'A single predictable forum avoids procedural disputes before the merits.',strong:'We cannot accept unilateral forum shopping.'},sourceAnchors:['J-02 — Dispute Resolution & Governing Law']
    },
    'H-05': {
      orientation:{tier:'Tier 1',negotiationHeat:'High',capitalToSpend:'High',typicalLandingZone:'Mandatory-law exclusions plus defined sub-caps for selected risks',corePrinciple:'Carve-outs must not consume the general cap.'},
      decisionTable:[{detectedPattern:'Long, unilateral or cascading carve-out list',recommendedAction:'Seek amendment',reason:'The economic limit may become illusory.',targetRung:'rung-1'}],
      sampleLanguage:'Only liability that cannot lawfully be limited is excluded from the general cap; specified data and IP claims are subject to the agreed sub-caps.',
      redlineMoves:['List every exclusion once.','Replace uncapped categories with defined sub-caps.','Prevent an indemnity from creating a second carve-out.'],
      pushback:{soft:'We can differentiate exceptional risks without making the cap ineffective.',strong:'Undefined or cascading carve-outs require approval.'},sourceAnchors:['H-05 — Exclusions from the Cap']
    },
    'H-06': {
      orientation:{tier:'Tier 1',negotiationHeat:'High',capitalToSpend:'High',typicalLandingZone:'Mutual exclusion with precise, limited recoverable heads',corePrinciple:'Enumerated loss heads must not reverse the negotiated exclusion.'},
      decisionTable:[{detectedPattern:'Customer-only exclusion or indemnity includes indirect/profit losses',recommendedAction:'Seek amendment',reason:'The loss allocation is one-sided or internally inconsistent.',targetRung:'rung-1'}],
      sampleLanguage:'Neither party is liable for indirect or consequential loss, loss of profit, revenue or anticipated savings, except to the extent expressly included within an agreed sub-cap.',
      redlineMoves:['Make the exclusion mutual.','List negotiated recoverable heads expressly.','Align indemnity and cap provisions.'],
      pushback:{soft:'Mutual clarity on recoverable loss avoids argument over labels.',strong:'A one-way exclusion paired with broad Supplier loss heads is not acceptable.'},sourceAnchors:['H-06 — Consequential & Indirect Damages']
    },
    'E-03': {
      orientation:{tier:'Tier 1',negotiationHeat:'High',capitalToSpend:'High',typicalLandingZone:'Role-accurate obligations tied to documented processing and reasonable assistance',corePrinciple:'Data duties must follow the actual processing role, scope and applicable law.'},
      decisionTable:[{detectedPattern:'Absolute security, undefined data scope or unlimited assistance',recommendedAction:'Seek amendment',reason:'The obligation may exceed the service model and insurable exposure.',targetRung:'rung-1'}],
      sampleLanguage:'Supplier will process Personal Data only for the documented Services, apply appropriate technical and organisational measures and notify Customer without undue delay after confirming a Personal Data Breach.',
      redlineMoves:['Confirm controller/fiduciary and processor roles.','Define data, purpose, geography and retention.','Make assistance reasonable, scoped and cost-allocated.'],
      pushback:{soft:'The data terms should follow the actual processing activity and legal roles.',strong:'Absolute security or open-ended regulatory assistance requires privacy and leadership review.'},dealOverlays:['SaaS','Managed services','Offshore delivery','Regulated outsourcing'],supplements:['E-03-S1 DPDP','E-03-S2 GDPR cross-border'],sourceAnchors:['E-03 — Data Protection']
    },
    'F-01': {
      orientation:{tier:'Tier 1',negotiationHeat:'High',capitalToSpend:'High',typicalLandingZone:'Customer-specific deliverables on payment; Supplier background assets retained',corePrinciple:'The deal should transfer the paid result, not reusable tools, know-how or platform assets.'},
      decisionTable:[{detectedPattern:'Background IP, tools or improvements vest in Customer',recommendedAction:'Escalate',reason:'Reusable Supplier capability may be transferred.',targetRung:'rung-5'}],
      sampleLanguage:'Upon payment, Customer owns the expressly identified Customer-specific Deliverables. Supplier retains Background IP, tools, know-how and generic improvements and grants the licence necessary to use the Deliverables.',
      redlineMoves:['Separate Deliverables from Background IP.','Condition transfer on payment.','Limit embedded-IP licence to necessary use and preserve third-party terms.'],
      pushback:{soft:'The Customer receives the paid-for result while reusable Supplier assets remain available across engagements.',strong:'Transfer of Background IP or generic tools requires executive approval.'},dealOverlays:['Technology implementation','SaaS','AI-enabled services'],sourceAnchors:['F-01 — IP Ownership']
    },
    'B-01': {
      orientation:{tier:'Tier 1',negotiationHeat:'Medium',capitalToSpend:'High',typicalLandingZone:'Measurable critical SLAs, documented exclusions and credits as primary remedy',corePrinciple:'Service remedies must reflect measured operational failure without duplicative recovery.'},
      decisionTable:[{detectedPattern:'Unqualified metric, uncapped credits or single-miss termination',recommendedAction:'Seek amendment',reason:'Operational variance can become disproportionate liability or exit risk.',targetRung:'rung-1'}],
      sampleLanguage:'Service Levels are measured monthly against the agreed methodology and exclusions. Credits are capped and are the primary monetary remedy; termination requires sustained Critical Service Level failure after remediation.',
      redlineMoves:['Define measurement source and exclusions.','Cap credits and prevent double recovery.','Require sustained critical failure before termination.'],
      pushback:{soft:'Objective measurement and proportionate credits make the SLA operationally enforceable.',strong:'A single miss cannot create uncapped damages or immediate termination.'},dealOverlays:['Managed services','SaaS','Support'],sourceAnchors:['B-01 — Service Levels & Service Credits']
    },
    'C-05': {
      orientation:{tier:'Tier 2',negotiationHeat:'Medium',capitalToSpend:'Medium',typicalLandingZone:'Ordinary subcontracting permitted with Supplier responsibility and material-subcontractor notice',corePrinciple:'Govern material delivery risk without making routine delivery dependent on discretionary consent.'},
      decisionTable:[{detectedPattern:'Blanket prior consent or unrestricted subcontracting',recommendedAction:'Seek amendment',reason:'Either model can impair delivery or governance.',targetRung:'rung-2'}],
      sampleLanguage:'Supplier may use Affiliates and subcontractors while remaining responsible for their performance; Supplier will provide reasonable prior notice of material delivery subcontractors.',
      redlineMoves:['Replace blanket consent with notice or consent not unreasonably withheld.','Preserve Supplier responsibility.','Align subprocessors with data terms.'],
      pushback:{soft:'Material-subcontractor visibility can be provided without blocking ordinary resourcing.',strong:'Discretionary consent for every subcontractor is operationally unworkable.'},sourceAnchors:['C-05 — Subcontracting']
    },
    'H-01': {
      orientation:{tier:'Tier 2',negotiationHeat:'Medium',capitalToSpend:'Medium',typicalLandingZone:'Professional standard plus time-bound conformity cure',corePrinciple:'A warranty should promise controlled performance, not an absolute outcome.'},
      decisionTable:[{detectedPattern:'Perpetual, error-free, uninterrupted or fit-for-purpose warranty',recommendedAction:'Seek amendment',reason:'The clause creates an outcome guarantee.',targetRung:'rung-1'}],
      sampleLanguage:'Supplier warrants that the Services will be performed with reasonable skill and care and that identified Deliverables will materially conform to the agreed specification for thirty days after acceptance; re-performance is the primary remedy.',
      redlineMoves:['Remove absolute outcome language.','Time-limit conformity warranties.','Define cure and exclusive remedy.'],
      pushback:{soft:'A specific professional and conformity warranty is more testable than an absolute promise.',strong:'Perpetual or error-free performance cannot be warranted.'},sourceAnchors:['H-01 — Warranties']
    },
    'J-01': {
      orientation:{tier:'Tier 2',negotiationHeat:'Low–Medium',capitalToSpend:'Medium',typicalLandingZone:'Reciprocal protection, standard exclusions and proportionate survival',corePrinciple:'Confidentiality should protect both parties without obstructing necessary delivery and disclosure.'},
      decisionTable:[{detectedPattern:'One-way, perpetual or operationally absolute confidentiality',recommendedAction:'Seek amendment',reason:'The duty may be asymmetric or impossible to administer.',targetRung:'rung-2'}],
      sampleLanguage:'Each party will protect the other’s Confidential Information using reasonable care, disclose it only on a need-to-know basis and apply the standard exclusions and compelled-disclosure process.',
      redlineMoves:['Make duties reciprocal.','Add standard exclusions and permitted recipients.','Limit general survival while preserving trade-secret protection.'],
      pushback:{soft:'Reciprocal and administrable confidentiality protects both businesses.',strong:'A one-way or indefinite duty over all information is disproportionate.'},sourceAnchors:['J-01 — Confidentiality']
    },
    'J-03': {
      orientation:{tier:'Tier 2',negotiationHeat:'Medium',capitalToSpend:'Medium',typicalLandingZone:'Reciprocal consent with affiliate, reorganisation and business-transfer exceptions',corePrinciple:'Assignment controls should protect counterparty identity without blocking ordinary corporate transactions.'},
      decisionTable:[{detectedPattern:'Supplier-only consent restriction with broad Customer transfer rights',recommendedAction:'Seek amendment',reason:'The restriction is structurally one-sided.',targetRung:'rung-1'}],
      sampleLanguage:'Neither party may assign the Agreement without consent, not unreasonably withheld, except to an Affiliate or in connection with a merger, reorganisation or transfer of substantially all relevant business assets.',
      redlineMoves:['Make consent reciprocal.','Add affiliate and transaction exceptions.','Separate assignment from subcontracting and change-of-control notice.'],
      pushback:{soft:'Reciprocal exceptions preserve continuity while protecting both parties.',strong:'One-way assignment freedom is not acceptable.'},sourceAnchors:['J-03 — Assignment & Change of Control']
    }
  };

  function expandV3Module(item, packageVersion) {
    const detail=PLAYBOOK_V3_DETAILS[item.id]||{};
    const sourceLadder=(item.fallbackLadder||[]).filter(Boolean);
    const standard=sourceLadder.find(entry=>entry.rung==='standard')||sourceLadder[0];
    const fallback=sourceLadder.find(entry=>entry.rung==='fallback-1')||sourceLadder[1]||standard;
    const escalation=sourceLadder.find(entry=>entry.rung==='walk-away')||sourceLadder[sourceLadder.length-1]||fallback;
    const five=[
      standard&&rung('rung-1','Rung 1 · House position',standard.position||item.standardPosition||'',standard.recommendedDecision||'seek-amendment',{approvalRequired:false,knowledgeStatus:'source-summary'}),
      fallback&&fallback!==standard&&rung('rung-2','Rung 2 · Preferred fallback',fallback.position||item.standardPosition||'',fallback.recommendedDecision||'seek-amendment',{approvalRequired:false,knowledgeStatus:'source-summary'}),
      escalation&&escalation!==fallback&&rung('rung-5','Rung 5 · Walk-away / escalation',escalation.position||`Escalate where the clause defeats the core principle for ${item.title}.`,'escalate',{approvalRequired:true,approver:'Leadership / authorised risk owner',escalationOnly:true,knowledgeStatus:'source-summary'})
    ].filter(Boolean);
    return {
      ...item,
      revision:String(item.revision||packageVersion),
      orientation:detail.orientation||{tier:'Core',negotiationHeat:'Medium',capitalToSpend:'Medium',typicalLandingZone:item.standardPosition||'',corePrinciple:item.whyItMatters||''},
      decisionTable:(detail.decisionTable||[{detectedPattern:'Material departure from the stated house position',recommendedAction:'Seek amendment',reason:item.whyItMatters||'Verify the allocation against the matter context.',targetRung:'rung-1'}]).map((row,index)=>({id:row.id||(index===0?`${item.id}-primary`:`${item.id}-decision-${index+1}`),...row})),
      fallbackLadder:five,
      sampleLanguage:detail.sampleLanguage||standard?.position||item.standardPosition||'',
      redlineMoves:detail.redlineMoves||[...(item.checks||[])],
      pushback:detail.pushback||{soft:`We need the clause to preserve the stated ${item.title} principle.`,strong:`A material departure on ${item.title} requires approval.`},
      checklist:(item.checks||[]).map((text,index)=>({id:`${item.id}-check-${index+1}`,text,appliesWhen:'module-relevant'})),
      dealOverlays:detail.dealOverlays||['Technology and professional services'],
      supplements:detail.supplements||[],
      sourceAnchors:detail.sourceAnchors||[`${item.id} — ${item.title}`],
      knowledgeStatus:detail.orientation?'source-structured-summary':'operational-source-summary'
    };
  }

  function normalizeText(value) { return String(value || '').toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim(); }
  function stableCanonicalize(value) {
    if (Array.isArray(value)) return `[${value.map(stableCanonicalize).join(',')}]`;
    if (value && typeof value === 'object') return `{${Object.keys(value).filter(key=>key!=='contentHash').sort().map(key=>`${JSON.stringify(key)}:${stableCanonicalize(value[key])}`).join(',')}}`;
    return JSON.stringify(value ?? null);
  }
  function normalizePackage(raw) {
    if (!raw || !Array.isArray(raw.modules)) return null;
    const packageId=String(raw.packageId||raw.id||'').trim();const version=String(raw.version||'').trim();if(!packageId||!version)return null;
    const modules=raw.modules.map(item=>{const normalized={...item,id:String(item?.id||'').trim(),revision:String(item?.revision||version),title:String(item?.title||'').trim(),clauseTypes:Array.isArray(item?.clauseTypes)?item.clauseTypes.map(String):[],checks:Array.isArray(item?.checks)?item.checks.map(value=>typeof value==='string'?value:String(value?.text||'')):[],relatedModules:Array.isArray(item?.relatedModules)?item.relatedModules.map(String):[],fallbackLadder:Array.isArray(item?.fallbackLadder)?item.fallbackLadder.filter(Boolean):[],applicability:item?.applicability&&typeof item.applicability==='object'?item.applicability:{requiredAny:Array.isArray(item?.keywords)?item.keywords:[],minEvidence:1}};const enriched=expandV3Module(normalized,version);const alreadyV3=normalized.fallbackLadder.some(entry=>/^rung-[1-5]$/.test(String(entry?.rung||'')));return alreadyV3?{...enriched,...normalized,checklist:Array.isArray(item?.checklist)?item.checklist:enriched.checklist}:enriched;}).filter(item=>item.id&&item.title);
    if(!modules.length)return null;const operationalIds=new Set(modules.map(item=>item.id));const sourceModuleRegistry=(Array.isArray(raw.sourceModuleRegistry)?raw.sourceModuleRegistry:modules.map(item=>({id:item.id,title:item.title,sourceStatus:'indexed'}))).map(item=>({...item,operationalStatus:operationalIds.has(item.id)?'operational':'not-loaded'}));return{...raw,schemaVersion:'contract-cockpit-playbook/3',packageId,version,modules,sourceModuleRegistry};
  }
  function collectRuleHits(text,rules){return(rules||[]).map(String).filter(rule=>{const token=normalizeText(rule);return token&&text.includes(token);});}
  function includesAny(text,patterns){return patterns.some(pattern=>pattern.test(text));}
  function evaluateModule(moduleId,rawText,conceptModel=null){
    const text=String(rawText||'');const normalized=normalizeText(text);const evidence=[];const deviations=[];let relevant=false;
    const conceptKeyByModule={'H-03':'indemnity','H-04':'liabilityCap','B-02':'acceptance','A-04':'changeControl','I-02':'termination','I-03':'termination','J-02':'disputeResolution','J-03':'assignment','D-01':'fees','E-03':'dataProtection','E-04':'dataProtection','E-05':'dataProtection','F-01':'intellectualProperty','G-01':'intellectualProperty','B-01':'serviceLevels'};
    const conceptKey=conceptKeyByModule[moduleId]||'';const conceptItems=conceptKey?(conceptModel?.byConcept?.[conceptKey]||[]):[];
    const note=(label,pattern)=>{if(pattern.test(text)){evidence.push(label);return true;}return false;};
    if(moduleId==='H-03'){
      relevant=note('Indemnity undertaking detected',/\bindemnif(?:y|ies|ication)\b|\bhold harmless\b|\bdefend\b/i);
      if(relevant){
        const thirdParty=note('Third-party scope detected',/\bthird[- ]party\b/i);
        const general=note('General or first-party loss heads detected',/\b(?:all|any)\s+(?:suits?|actions?|proceedings?|claims?|damages?|liabilit(?:y|ies)|loss(?:es)?|fees?|costs?|expenses?)\b/i)||note('Breach, act, omission or negligence trigger detected',/\bacts?,?\s+omissions?|\bbreach(?:es)?\b|\bnegligence\b/i);
        if(general&&!thirdParty)deviations.push({id:'first-party',label:'Broad direct/general indemnity — not limited to third-party claims'});
        if(note('Consequential or profit loss head detected',/\b(?:indirect|incidental|special|consequential|punitive)\b|\bloss of profit/i))deviations.push({id:'broad-heads',label:'Consequential, special or profit-loss heads appear within the indemnity'});
        if(!includesAny(text,[/\bcontrol (?:of )?(?:the )?defen[cs]e\b/i,/\bconduct (?:of )?(?:the )?claim\b/i]))deviations.push({id:'defence-control',label:'Defence-control mechanics not identified in this clause'});
        if(!/\bsettle(?:ment)?\b/i.test(text))deviations.push({id:'settlement',label:'Settlement-consent protection not identified in this clause'});
        if(!/\bnotice\b/i.test(text))deviations.push({id:'notice',label:'Claim-notice mechanics not identified in this clause'});
      }
    }else if(moduleId==='B-02'){
      const acceptanceEffect=/\b(?:accept(?:ed|ance)|reject(?:ed|ion))\b/i.test(text)&&/\b(?:within|after|expiry|expiration)\b[^.;]{0,90}\b(?:day|business day)s?\b/i.test(text);
      const deemedEffect=/\b(?:if|unless)\b[^.;]{0,180}\b(?:reject|object|notify)\b[^.;]{0,180}\b(?:considered|treated|regarded|automatically|deemed)\s+(?:as\s+)?accepted\b/i.test(text)
        || /\b(?:considered|treated|regarded|automatically|deemed)\s+(?:as\s+)?accepted\b/i.test(text);
      relevant=acceptanceEffect||deemedEffect||/\bacceptance criteria|acceptance test\b/i.test(text);
      if(acceptanceEffect)evidence.push('Acceptance or rejection window detected');if(deemedEffect){evidence.push('Acceptance by silence detected');deviations.push({id:'deemed-acceptance',label:'Automatic/deemed acceptance mechanism detected — verify criteria and rejection mechanics'});}
      if(relevant&&!/\b(?:objective|criteria|specification|requirements?)\b/i.test(text))deviations.push({id:'subjective-acceptance',label:'Objective acceptance criteria not identified in this clause'});
    }else if(moduleId==='A-04'){
      const modification=/\b(?:modify|modified|modification|amend|amendment|vary|variation|change)\b/i.test(text);
      const impact=/\b(?:scope|services?|fees?|price|charges?|schedule|timeline|delivery date|responsibilit(?:y|ies))\b/i.test(text);
      const approval=/\b(?:mutual|both parties|written agreement|signed|approval|consent)\b/i.test(text);
      relevant=modification&&(impact||approval);
      if(relevant)evidence.push('Contract-change mechanism detected');
      if(relevant&&!impact)deviations.push({id:'impact-assessment',label:'Price, timing and scope impact assessment not identified'});
      if(relevant&&!approval)deviations.push({id:'approval',label:'Mutual written approval not identified'});
    }else if(moduleId==='I-03'){
      const termination=/\bterminat(?:e|es|ed|ion)\b/i.test(text);const breach=/\b(?:breach|default|insolven|bankrupt|liquidat|ceases? business)\b/i.test(text);
      relevant=termination&&breach;if(relevant)evidence.push('Cause-based termination trigger detected');
      if(relevant&&!/\b(?:cure|remed(?:y|ied)|notice period|days? (?:to|for) remed)\b/i.test(text))deviations.push({id:'no-cure',label:'Cause right detected without an express cure process in this clause'});
      if(relevant&&/\bimmediate(?:ly)?\b/i.test(text))deviations.push({id:'immediate-cause',label:'Immediate termination trigger detected'});
    }else if(moduleId==='I-02'){
      const termination=/\bterminat(?:e|es|ed|ion)\b/i.test(text);const convenience=/\b(?:at any time|without (?:cause|reason)|without assigning any reason|for convenience|upon notice)\b/i.test(text);
      relevant=termination&&convenience;if(relevant)evidence.push('No-cause/convenience termination effect detected');
      if(relevant&&!/\b(?:either party|each party|both parties|mutual)\b/i.test(text))deviations.push({id:'one-way-convenience',label:'Potentially one-way convenience termination'});
      if(relevant&&!/\b(?:committed costs?|work performed|accrued fees?|termination charge)\b/i.test(text))deviations.push({id:'stranded-cost',label:'Committed-cost or work-performed protection not identified'});
    }else if(moduleId==='J-02'){
      const court=/\b(?:submits?|consents?)\s+to\b[^.;]{0,120}\bjurisdiction\b|\b(?:exclusive|non-exclusive)\s+jurisdiction\b|\b(?:disputes?|claims?|proceedings?)\b[^.;]{0,180}\b(?:courts?|jurisdiction|venue|forum)\b/i.test(text)&&!/\bcourt of auditors?\b|\bcourt of competent jurisdiction\b[^.;]{0,150}\b(?:invalid|unenforceable|severab)/i.test(text);const arbitration=global.ContractCockpitAnalysis?.assessOperativeAssertion?.(text,{mention:/\b(?:arbitrat(?:e|ion)|ICC|SIAC|LCIA|DIAC)\b/i,operative:/\b(?:shall|must|will|may|refer|submit|elect|binding|final)\b[^.;]{0,220}\b(?:arbitrat(?:e|ion)|ICC|SIAC|LCIA|DIAC)\b|\b(?:arbitrat(?:e|ion)|ICC|SIAC|LCIA|DIAC)\b[^.;]{0,160}\b(?:shall|must|will|binding|final|seat|rules?)\b/i})?.asserted===true;
      relevant=court||arbitration;if(court)evidence.push('Court forum detected');if(arbitration)evidence.push('Arbitration forum detected');
      if(court&&arbitration&&/\b(?:option|may\b[^.;]{0,80}\belect|may\b[^.;]{0,80}\bchoose|discretion)\b/i.test(text))deviations.push({id:'forum-option',label:'Unilateral or multi-forum optionality detected'});
    }else if(moduleId==='E-04'){
      relevant=/\b(?:information security|security controls?|iso 27001|technical and organisational measures|security requirements?)\b/i.test(text);if(relevant)evidence.push('Information-security commitment detected');if(/\b(?:all|any)\s+(?:customer )?polic(?:y|ies)|absolute security|prevent all|ensure no breach\b/i.test(text))deviations.push({id:'absolute-security',label:'Absolute or dynamically incorporated security obligation detected'});
    }else if(moduleId==='E-05'){
      relevant=/\b(?:security incident|personal data breach|data breach|cyber incident|incident response)\b/i.test(text);if(relevant)evidence.push('Security-incident duty detected');if(/\b(?:immediate(?:ly)?|within\s+(?:1|one|2|two|4|four|6|six|12|twelve)\s+hours?)\b/i.test(text))deviations.push({id:'accelerated-notice',label:'Accelerated incident notice requires operational verification'});
    }else if(moduleId==='G-01'){
      relevant=/\b(?:ai|ai system|ai tool|ai output|artificial intelligence|machine learning|generative ai|ai model|model output|training data|automated decision)\b/i.test(text);if(relevant)evidence.push('AI component or use detected');if(/\b(?:train|training)\b[^.;]{0,140}\b(?:customer|client|personal|confidential)\s+data\b|\b(?:accurate|error-free|non-infringing|compliant with all)\b/i.test(text))deviations.push({id:'ai-exposure',label:'AI training, output or absolute warranty exposure detected'});
    }
    if(conceptKey&&conceptModel){
      if(['B-02','A-04','J-02','H-03','H-04','J-03','D-01','E-03','F-01','B-01'].includes(moduleId))relevant=conceptItems.length>0;
      if(['I-02','I-03'].includes(moduleId))relevant=conceptItems.some(item=>moduleId==='I-03'?item?.facts?.cause:item?.facts?.convenience);
      conceptItems.slice(0,3).forEach(item=>{if(item.mechanism&&!evidence.includes(item.mechanism))evidence.push(item.mechanism);});
    }
    return{relevant,evidence,deviations:deviations.map(item=>({...item,decisionRowId:`${moduleId}-primary`})),conceptEvidence:conceptItems};
  }
  function candidateModules(pkg,clause,matter,options={}){
    if(!pkg||!clause||!Array.isArray(pkg.modules))return[];const confirmedRole=String(matter?.role||'Neutral');const roleMatched=!pkg.role||confirmedRole===pkg.role;if(!roleMatched&&!options.previewRole)return[];
    const heading=normalizeText(clause.heading);const rawBody=String(clause.body||'').slice(0,50000);const body=normalizeText(rawBody);const text=`${heading} ${body}`;const conceptModel=global.ContractCockpitAnalysis?.detectLegalConcepts?.([{...clause,body:rawBody}])||null;
    const contextText=normalizeText([matter?.deliveryModel,matter?.sector,matter?.dealType,matter?.dataProfile,matter?.geography,matter?.strategyNote].filter(Boolean).join(' '));
    return pkg.modules.map(item=>{const rules=item.applicability||{};const requiredHits=collectRuleHits(text,rules.requiredAny);const headingHits=collectRuleHits(heading,rules.requiredAny);const prohibitedHits=collectRuleHits(text,rules.excludeAny);const requiredCount=Number(rules.requiredCount||rules.minEvidence||1);const typeMatch=(item.clauseTypes||[]).some(type=>normalizeText(type)===normalizeText(clause.type));const structured=evaluateModule(item.id,`${clause.heading||''}. ${rawBody}`,conceptModel);if(prohibitedHits.length||(!structured.relevant&&requiredHits.length<requiredCount))return null;const legacyDeviations=(rules.issueRules||[]).filter(rule=>collectRuleHits(text,rule.any).length).map(rule=>({id:rule.id,label:rule.label,decisionRowId:`${item.id}-primary`}));const deviations=[...new Map([...legacyDeviations,...structured.deviations].map(entry=>[entry.id,entry])).values()];const overlayHits=(item.dealOverlays||[]).filter(overlay=>contextText.includes(normalizeText(overlay)));const contextBoost=overlayHits.length*2+((item.id==='G-01'&&/\bai\b|artificial intelligence|machine learning/.test(contextText))?4:0)+((['E-03','E-04','E-05'].includes(item.id)&&/data|privacy|saas|cloud|offshore|regulated/.test(contextText))?2:0);const score=requiredHits.length*3+headingHits.length*2+(typeMatch?2:0)+(structured.relevant?4:0)+deviations.length*2+contextBoost;const reasons=[...new Set([...structured.evidence,...requiredHits.slice(0,3).map(hit=>`Source signal: ${hit}`),...overlayHits.map(hit=>`Matter overlay: ${hit}`)])];if(typeMatch)reasons.push(`Clause type: ${clause.type}`);return{module:item,score,matchStrength:score>=10?'Strong':score>=5?'Moderate':'Possible',reasons,deviations,roleMatched,previewRole:roleMatched?'':pkg.role||'',issueEvidence:structured.evidence,conceptEvidence:structured.conceptEvidence||[],contextBoost};}).filter(Boolean).sort((a,b)=>b.score-a.score||a.module.id.localeCompare(b.module.id));
  }

  function candidateSourceModules(pkg,clause){
    if(!pkg||!clause)return[];
    const loaded=new Set((pkg.modules||[]).map(item=>item.id));const text=normalizeText(`${clause.heading||''}. ${clause.body||''}`);
    return (pkg.sourceModuleRegistry||[]).filter(item=>!loaded.has(item.id)).map(item=>{
      const hits=(item.topicSignals||[]).filter(signal=>{const token=normalizeText(signal);return token.length>2&&new RegExp(`(?:^|\\s)${token.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}(?:$|\\s)`).test(text);});
      return hits.length?{...item,matchStrength:hits.length>1?'Strong source signal':'Source signal',operationalStatus:'not-loaded',reasons:hits.slice(0,4).map(hit=>`Source signal: ${hit}`),score:hits.length}:null;
    }).filter(Boolean).sort((a,b)=>b.score-a.score||a.id.localeCompare(b.id));
  }

  const normalizedBuiltin=normalizePackage(SUPPLIER_SERVICES_CORE);
  global.ContractCockpitPlaybook=Object.freeze({BUILTIN_PACKAGES:Object.freeze([Object.freeze(normalizedBuiltin)]),normalizePackage,candidateModules,candidateSourceModules,evaluateModule,stableCanonicalize,canonicalPackageContent(pkg){return stableCanonicalize(normalizePackage(pkg));},getModule(pkg,moduleId){return pkg?.modules?.find(item=>item.id===moduleId)||null;}});
})(typeof globalThis !== 'undefined' ? globalThis : this);
