/* Contract Cockpit v7.6.1: pure trust, source-provenance and review-identity helpers. */
(function attachContractCockpitReview(root) {
  const clean=value=>String(value||'').replace(/\s+/g,' ').trim();
  const key=value=>clean(value).toLocaleLowerCase().replace(/[^\p{L}\p{N}]+/gu,'-').replace(/^-|-$/g,'');
  const escapeRegExp=value=>String(value||'').replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
  const SOURCE_WARNING_RULES=Object.freeze([
    {kind:'tracked-revisions',material:true,pattern:/tracked changes|tracked revisions|insertions included|deletions excluded/i},
    {kind:'omitted-word-content',material:true,pattern:/not included in clause analysis|text boxes detected|embedded or externally linked word content|content controls detected|footnotes? (?:were|are) not analysed|endnotes? (?:were|are) not analysed/i},
    {kind:'mapping-integrity',material:true,pattern:/extraction integrity concern|numbering definitions not found|fingerprint unavailable/i},
    {kind:'insufficient-source',material:true,pattern:/very little text|no reviewable text|source appears incomplete/i}
  ]);
  function classifySourceWarnings(warnings=[]){const records=warnings.map((warning,index)=>{const rule=SOURCE_WARNING_RULES.find(item=>item.pattern.test(String(warning||'')));return{id:`source-warning-${index+1}`,warning:String(warning||''),kind:rule?.kind||'advisory',material:!!rule?.material};});const materialRecords=records.filter(item=>item.material);return{records,material:materialRecords.map(item=>item.warning),materialRecords,hasTrackedChanges:materialRecords.some(item=>item.kind==='tracked-revisions'),hasOmittedWordParts:materialRecords.some(item=>item.kind==='omitted-word-content'),requiresAssurance:materialRecords.length>0};}
  function canonicalTermFactKey(term){return`term:${key(term)||'unknown'}`;}
  function scoreDefinedTermCandidate(term,contexts=[],options={}){const value=clean(term),samples=contexts.map(context=>clean(typeof context==='string'?context:context?.sentence||context?.text||'')).filter(Boolean);let score=0;const reasons=[];const add=(points,reason)=>{score+=points;reasons.push(reason);};if(/^[A-Z][\p{L}\p{N}'’&/-]+(?:\s+[A-Z][\p{L}\p{N}'’&/-]+)+$/u.test(value))add(2,'capitalised multiword expression');else if(/^[A-Z][\p{L}\p{N}'’&/-]{3,}$/u.test(value))add(1,'consistently capitalised expression');if(samples.some(text=>new RegExp(`\\bthe\\s+${escapeRegExp(value)}\\b`,'i').test(text)))add(1,'used as a specific contractual object');if(samples.some(text=>new RegExp(`\\b(?:shall|must|will|may|undertakes? to|is required to)\\b[^.;]{0,150}\\b${escapeRegExp(value)}\\b|\\b${escapeRegExp(value)}\\b[^.;]{0,120}\\b(?:shall|must|will|may)\\b`,'i').test(text)))add(2,'used in operative drafting');if(samples.some(text=>new RegExp(`\\b(?:if|when|until|unless|subject to|following)\\b[^.;]{0,130}\\b${escapeRegExp(value)}\\b`,'i').test(text)))add(1,'used as a condition or trigger');if(samples.some(text=>/\b(?:Schedule|Annex(?:ure)?|Exhibit|Appendix|Statement of Work)\b/i.test(text)))add(1,'used across document structure');if(Number(options.spread||options.clauseCount||0)>=2)add(1,'used in multiple clauses');return{score,structural:score>=4,confidence:score>=6?'High':score>=4?'Moderate':'Low',reasons};}
  function normalizeSourceSpans(spans=[]){return spans.filter(span=>span?.blockId).map(span=>({blockId:String(span.blockId),start:Math.max(0,Number(span.start)||0),end:Math.max(0,Number(span.end)||0),kind:span.kind||'extracted'}));}
  function fullBlockSpans(blockIds=[],blocks=[]){const byId=new Map(blocks.map(block=>[block.id,block]));return[...new Set(blockIds)].map(blockId=>{const text=String(byId.get(blockId)?.exactText??byId.get(blockId)?.text??'');return{blockId,start:0,end:text.length,kind:'extracted'};});}
  function materializeSpans(spans=[],blocks=[]){const byId=new Map(blocks.map(block=>[block.id,block]));return normalizeSourceSpans(spans).map(span=>{const text=String(byId.get(span.blockId)?.exactText??byId.get(span.blockId)?.text??''),start=Math.min(text.length,span.start),end=Math.min(text.length,Math.max(start,span.end||text.length));return{...span,start,end,text:text.slice(start,end)};});}
  function splitSourceSpans(spans=[],blocks=[],marker=''){const material=materializeSpans(spans,blocks),joined=material.map(item=>item.text).join('\n'),at=joined.indexOf(String(marker||''));if(at<=0)return{exact:false,left:normalizeSourceSpans(spans),right:normalizeSourceSpans(spans),reason:'marker-not-found-in-mapped-source'};const left=[],right=[];let cursor=0;for(const item of material){const blockStart=cursor,blockEnd=cursor+item.text.length;if(at>=blockEnd)left.push({blockId:item.blockId,start:item.start,end:item.end,kind:'lawyer-corrected-span'});else if(at<=blockStart)right.push({blockId:item.blockId,start:item.start,end:item.end,kind:'lawyer-corrected-span'});else{const cut=item.start+(at-blockStart);if(cut>item.start)left.push({blockId:item.blockId,start:item.start,end:cut,kind:'lawyer-corrected-span'});if(cut<item.end)right.push({blockId:item.blockId,start:cut,end:item.end,kind:'lawyer-corrected-span'});}cursor=blockEnd+1;}return{exact:!!left.length&&!!right.length,left,right,reason:''};}
  function mergeSourceSpans(...collections){const seen=new Set(),distinct=collections.flat().map(item=>({...item,kind:'lawyer-corrected-span'})).filter(item=>{const id=`${item.blockId}:${item.start}:${item.end}`;if(seen.has(id))return false;seen.add(id);return true;}),merged=[];distinct.sort((a,b)=>String(a.blockId).localeCompare(String(b.blockId))||a.start-b.start).forEach(item=>{const prior=merged[merged.length-1];if(prior&&prior.blockId===item.blockId&&item.start<=prior.end){prior.end=Math.max(prior.end,item.end);return;}merged.push({...item});});return merged;}
  root.ContractCockpitReview=Object.freeze({SOURCE_WARNING_RULES,canonicalTermFactKey,classifySourceWarnings,fullBlockSpans,materializeSpans,mergeSourceSpans,scoreDefinedTermCandidate,splitSourceSpans});
})(typeof globalThis!=='undefined'?globalThis:this);
